### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by JimScope** [roshnet/blogstate-refactor#1]
Create a setup.py file for easy install

**Comment by roshnet** [comment]
Hi @JimScope! Regarding this project, I'm not sure if people would prefer installing it via the command line, since they could use the web app directly :stuck_out_tongue:

However, I had this idea in my todo-list to create a pip-installable CLI tool that consumes the API, and posts the content of a file as a blog post under your account. Let me know if you have any comments regarding that.

**Comment by JimScope** [comment]
It's a very good idea. The api could be used to provide data and posts to static blogs, similar to how contentful works. I have an idea in my head to implement a similar one, but to provide data (and logic) to small static ecommerces.
